export const DEFAULT_API_URL = 'https://socket.put.io/socket/sockjs'

export const WEBSOCKET_CLOSEEVENT_CODE = {
  NORMAL_CLOSURE: 1000,
  SERVER_ERROR: 1011,
  UNAUTHORIZED: 4001,
} as const

export const WEBSOCKET_ERROREVENT_CODE = {
  CONNECTION_REFUSED: 'ECONNREFUSED',
} as const

const HEARTBEAT_INTERVAL_IN_SECONDS = 10
const HEARTBEAT_LATENCY_ASSUMPTION_IN_SECONDS = 2

export const HEARTBEAT_TIMER =
  (HEARTBEAT_INTERVAL_IN_SECONDS + HEARTBEAT_LATENCY_ASSUMPTION_IN_SECONDS) *
  1000
